name: fast_ui_example
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fast_ui:
    path: ../
  device_preview: ^1.0.0
  url_launcher: ^6.0.18
  font_awesome_flutter: ^10.0.0-beta
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  rexios_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
