name: fast_state
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/Rexios80/fast_ui

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  rexios_lints: ^1.0.0
