name: fast_rx_flutter
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/Rexios80/fast_ui/tree/master/fast_rx_flutter

environment:
  sdk: ">=2.18.4 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  fast_rx:
    path: ../fast_rx

dev_dependencies:
  flutter_test:
    sdk: flutter

  rexios_lints: ^4.0.0
