name: fast_rx_persistence
description: An interface for implementing fast_rx key/value store persistence
version: 0.1.0
homepage: https://github.com/Rexios80/fast_ui/tree/master/fast_rx_persistence

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  fast_rx:
    path: ../fast_rx

dev_dependencies:
  test: ^1.19.0
  rexios_lints: ^2.0.0
