name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Setup flutter
        uses: subosito/flutter-action@v2

      - name: Build 🔧
        run: |
          cd fast_ui/example
          flutter pub get
          flutter build web

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: fast_ui/example/build/web
