name: Static Analysis
on:
  push:
  pull_request:

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: subosito/flutter-action@v2
      - run: |
          flutter pub global activate puby
          puby get
          flutter format . --set-exit-if-changed
          flutter analyze
