name: Static Analysis
on:
  push:
  pull_request:

jobs:
  static-analysis:
    strategy:
      matrix:
        project:
          ["fast_extensions", "fast_nav", "fast_overlays", "fast_rx", "fast_ui"]
    defaults:
      run:
        working-directory: ${{ matrix.project }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: subosito/flutter-action@v2
      - name: Pub get
        run: flutter pub get
      - name: Format
        run: flutter format . --set-exit-if-changed
      - name: Analyze
        run: flutter analyze
      - name: Pana
        run: |
          flutter pub global activate pana
          pana --no-warning --exit-code-threshold 0
      - name: Embedme
        run: |
          npm install embedme
          npx embedme README.md --verify
