name: Test coverage
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test-coverage:
    strategy:
      matrix:
        project: ["fast_nav", "fast_overlays", "fast_rx"]
    defaults:
      run:
        working-directory: ${{ matrix.project }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: subosito/flutter-action@v2
      - run: flutter pub get && flutter test --coverage
      - uses: codecov/codecov-action@v2
        with:
          flags: ${{ matrix.project }}
